config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
    }

  root 'tops#index' 
  resources :tops, only: [:index]

  resources :users, only: [:show]

  
  resources :categories, only: [:show]
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :post_category_relations, only: [:create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :post_category_relations, dependent: :destroy
    has_many :posts, through: :post_category_relations

    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :post_category_relations, dependent: :destroy
    has_many :categories, through: :post_category_relations



    mount_uploader :image, ImageUploader

    validates :taste, :service, :cost, :atmosphere, :access, numericality:{
        less_than_or_equal_to: 5,
        greater_than_or_equal_to: 1
    }, presence: true 


    def average
        a = (taste + service + cost + atmosphere + access) / 5.0
        b = a.round(1)

        return b
    end

    def average_check
        a = (taste + service + cost + atmosphere + access) / 5.0
        b = a.round(1)
        if b == 5
            return "人生で一回は行くべき最高の店"
        elsif  b < 5 and b >= 4
            return "そのカテゴリ―で名をはせる店"
        elsif b < 4 and b >= 3
            return "人気のあるおいしい店"
        elsif b < 3 and b >= 2
            return "可もなく不可もない店"
        elsif b < 2 and b >= 1
            return "もう行かないと思われる店"
        else
            
        end
    end

    def taste_check
        if taste >= 5
            return "3150"
            
        elsif 5 > taste and taste >= 4
            return "まあまあうまい"
            
        else
            return ""
            
        end
    end

end

app/models/post_category_relation.rb
class PostCategoryRelation < ApplicationRecord
  belongs_to :post
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  validates :name, presence: true 

  mount_uploader :image, ImageUploader

  
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

  # ログイン済ユーザーのみにアクセスを許可する
  before_action :authenticate_user!  

  # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとimageのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  end

  # ログイン後に遷移するpathを設定
  def after_sign_in_path_for(resource)
    posts_path 
  end
 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def show
        @category = Category.find(params[:id])
        @categories = Category.all
        @posts = Post.all
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        post = Post.find(params[:post_id])
        @comment = post.comments.build(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
          flash[:success] = "コメントしました"
          redirect_back(fallback_location: root_path)
        else
          flash[:success] = "コメントできませんでした"
          redirect_back(fallback_location: root_path)
        end
      end
    
      private
    
        def comment_params
          params.require(:comment).permit(:comment)
        end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        @like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
    end
    
      def destroy
        @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  

  # GET /posts
  # GET /posts.json
  def index
    @category = Category.all
    if params[:search] != nil && params[:search] != ''
      #部分検索かつ複数検索(後日user検索も)
      @posts = Post.where("store_name LIKE ? ", "%" + params[:search] + "%").or(Post.where("review LIKE ? ", "%" + params[:search] + "%"))
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @like = Like.new
    @comments = @post.comments
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:image, :store_name, :review, :taste, :service, :cost, :atmosphere, :access, category_ids: [])
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

    before_action :authenticate_user!,  except: [:index]


    def index
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id]) 
    @posts = Post.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_category_relations_helper.rb
module PostCategoryRelationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <%# 画像 %>
    <div class="form-group row">
      <%= form.label :image, class:'col-md-3 col-form-label' %>
      <div class="col-md-9">
        <%= form.file_field :image %>
      </div>
    </div>

    <%# 店の名前 %>
    <div class="form-group row">
      <%= form.label :store_name, class:'col-md-3 col-form-label' %>
      <div class="col-md-9">
        <%= form.text_field :store_name, class: "form-control" %>
      </div>
    </div>

    <%# テキスト %>
    <div class="form-group row">
      <%= form.label :review, class:'col-md-3 col-form-label' %>
      <div class="col-md-9">
        <%= form.text_area :review, class: "form-control", rows: "8" %>
      </div>
    </div>

    
    <%# 評価 %>
    <div class="form-group" id="star1">
      <%= form.label :taste, class:'col-md-3 col-form-label' %>
      <%= form.hidden_field :taste, id: :review_star %>
    </div>

    <div class="form-group" id="star2">
      <%= form.label :service, class:'col-md-3 col-form-label' %>
      <%= form.hidden_field :service, id: :review_star %>
    </div>

    <div class="form-group" id="star3">
      <%= form.label :cost, class:'col-md-3 col-form-label' %>
      <%= form.hidden_field :cost, id: :review_star %>
    </div>

    <div class="form-group" id="star4">
      <%= form.label :atmosphere, class:'col-md-3 col-form-label' %>
      <%= form.hidden_field :atmosphere, id: :review_star %>
    </div>

    <div class="form-group" id="star5">
      <%= form.label :access, class:'col-md-3 col-form-label' %>
      <%= form.hidden_field :access, id: :review_star %>
    </div>

    <%# 評価javascript %>
    <script>
      $('#star1').raty({
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'post[taste]',
      });
    </script> 

     <script>
      $('#star2').raty({
        size     : 45,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'post[service]',
      });
    </script> 

    <script>
      $('#star3').raty({
        size     : 45,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'post[cost]',
      });
    </script> 

    <script>
      $('#star4').raty({
        size     : 45,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'post[atmosphere]',
      });
    </script> 

    <script>
      $('#star5').raty({
        size     : 45,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'post[access]',
      });
    </script> 

    <%# カテゴリー %>
    <div class="form-group row">
      <div class="col-md-9">
        <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
      </div>
    </div>
    


    <%# ボタン %>
    <div class="form-group row justify-content-end">
      <div class="col-md-9">
        <%= form.submit '投稿する', class:"btn btn-success" %>
      </div>
    </div>

  <% end %>
</div>

 

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "index", :media => "all" %>

<div class="container">
  <%# 検索 %>
  <form class="form-inline my-2 my-lg-4 ">
    <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
      <%= text_field_tag :search, "", {class:"form-control mr-sm-2"} %>
      <%= submit_tag '検索する', {class:"btn btn-outline-success my-2 my-sm-0"} %>
    <% end %>  
  </form>

  <div class="row">
    <%# カテゴリ― %>
    <div class="card col-md-3" style="width: 200px">
      <% @category.each do |c| %>
      <%= link_to c.name, category_path(c.id), class:"category_list" %>
      <% end %>
    </div>

    <%# 投稿 %>
    <div class="col-md-9">
      <% @posts.each do |post| %>
        <div class="card">
          <h5 class="card-title"><%= link_to post.user.name, user_path(post.user.id) %></h5>
          <%= image_tag post.image_url, class:"card-img-top", size: '500×320' %>
          <div class="card-body">
            <h5 class="card-title"><%= post.store_name %></h5>
            <div class="badge badge-pill badge-dark">
              <% post.categories.each do |category| %>
                <%= category.name %>
              <% end %>
            </div>
            <p class="card-text">
              <span id="star-rate-<%= post.id %>"></span> | <%= post.average_check %>
                <script>
                  $('#star-rate-<%= post.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= post.average %>,
                  });
                </script>
              <div class="fas fa-heart" style="color: Pink;"></div><%= post.liked_users.count %>
            </p>
            <% if post.user.id == current_user.id %>
            <div class="row">
              <div class="m-1"><%= link_to '詳細', post, class:"btn btn-outline-dark" %></div>
              <div class="m-1"><%= link_to '編集', edit_post_path(post), class:"btn btn-outline-dark" %></div>
              <div class="m-1"><%= link_to '消去', post, method: :delete, data: { confirm: '消去しますか?' }, class:"btn btn-outline-dark" %></div>
            </div>
            <% else %>
              <button type="button" class="btn btn-outline-secondary"><%= link_to '詳細へ', post %></button>
            <% end %>
            <p class="text-right"><%= post.updated_at.strftime("%m月%d日 %H:%M") %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container mt-3">
  <div class="col-5">
    <%= image_tag @post.image_url, size:'500×320' %>
  </div>
  <div class="row">
    <strong class='col-md-3 col-form-label'>Name:</strong>
    <div class="col-md-9">
      <%= @post.user.name %>
    </div>
  </div>

  <div class="row">
    <strong class='col-md-3 col-form-label'>Store name:</strong>
    <div class="col-md-9">
      <%= @post.store_name %>
    </div>
  </div>

  <div class="row">
    <strong class='col-md-3 col-form-label'>Review:</strong>
    <div class="col-md-9">
      <%= @post.review %>
    </div>
  </div>

  <div class="row">
    <strong class="col-md-3 col-form-label">Taste:</strong>
    <div class="col-md-9" id="star-rate-1">
      <script>
        $('#star-rate-1').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @post.taste %>,
        });
      </script>
    </div>
  </div>
  
  <div class="row">
    <strong class="col-md-3 col-form-label">Service:</strong>
    <div class="col-md-9" id="star-rate-2">
      <script>
        $('#star-rate-2').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @post.service %>,
        });
      </script>
    </div>
  </div>

  <div class="row">
    <strong class="col-md-3 col-form-label">Cost:</strong>
    <div class="col-md-9" id="star-rate-3">
      <script>
        $('#star-rate-3').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @post.cost %>,
        });
      </script>
    </div>
  </div>

  <div class="row">
    <strong class="col-md-3 col-form-label">Atmosphere:</strong>
    <div class="col-md-9" id="star-rate-4">
      <script>
        $('#star-rate-4').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @post.atmosphere %>,
        });
      </script>
    </div>
  </div>
  
  <div class="row">
    <strong class="col-md-3 col-form-label">Access:</strong>
    <div class="col-md-9" id="star-rate-5">
      <script>
        $('#star-rate-5').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @post.access %>,
        });
      </script>
    </div>
  </div>

  <div class="row">
    <strong class="col-md-3 col-form-label">Average:</strong>
    <div class="col-md-9" id="star-rate">
      <script>
        $('#star-rate').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @post.average %>,
        });
      </script>
    </div>
  </div>

  <div class="badge badge-pill badge-dark">
    <% @post.categories.each do |category| %>
      <%= category.name %>
    <% end %>
  </div>

  <div class="row">
    <strong class="col-md-3 col-form-label">like count:</strong>
    <div class="col-md-3 col-form-label"><%= @post.likes.count %></div>
  </div>
  <div>
    <% if current_user.already_liked?(@post) %>
      <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete, class:"btn btn-outline-dark" %>
    <% else %>
      <%= button_to 'いいね', post_likes_path(@post), class:"btn btn-outline-dark" %>
    <% end %>
  </div>

  <div class="row">
    <strong class="col-md-3 col-form-label">like user</strong>
    <% @post.liked_users.each do |user| %>
      <li class="col-md-9 col-form-label"><%= user.name %></li>
    <% end %>
  </div>

  <div class="comment-wrapper">
    <strong>コメント一覧</strong>
    <% @comments.each do |c| %>
      <div class="row">
        <strong class="col-md-3 col-form-label">
        <%= c.user.name unless c.user.blank? %>
        </strong>
        <div class="col-md-9">
          <%= c.comment %>
        </div>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
        <div class="form-group row">
          <%= f.text_area :comment, class: "form-control", rows: "8" %>
          <%= button_tag type: "submit", class:"btn btn-success mt-2" do %>
            <i class="far fa-comments"></i> コメントする
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="mb-5">
    <%= link_to '編集', edit_post_path(@post), class:"btn btn-outline-dark" %>
    <%= link_to "ホーム", posts_path, class:"btn btn-outline-dark" %>
  </div>
</div>